[repository]
name = "hyprland-plugins"
authors = ["Vaxry"]
commit_pins = []

[hyprbars]
description = "A plugin to add title bars to windows"
authors = ["Vaxry"]
output = "hyprbars/hyprbars.so"
build = [
    "make -C hyprbars all",
]


[hyprpill]
description = "A plugin to add animated pill grabbers to windows"
authors = ["Vaxry"]
output = "hyprpill/hyprpill.so"
build = [
    "make -C hyprpill all",
]
