[borders-plus-plus]
description ="A plugin to add more borders to windows."
version = "1.0"
authors = ["Vaxry"]

[borders-plus-plus.build]
output = "borders-plus-plus/borders-plus-plus.so"
steps = [
    "make -C borders-plus-plus all",
]

[csgo-vulkan-fix]
description = "A plugin to fix incorrect mouse offsets on csgo in Vulkan"
version = "1.0"
authors = ["Vaxry"]

[csgo-vulkan-fix.build]
output = "csgo-vulkan-fix/csgo-vulkan-fix.so"
steps = [
    "make -C csgo-vulkan-fix all",
]

[hyprbars]
description = "A plugin to add title bars to windows"
version = "1.0"
authors = ["Vaxry"]

[hyprbars.build]
output = "hyprbars/hyprbars.so"
steps = [
    "make -C hyprbars all",
]


[hyprpill]
description = "A plugin to add animated pill grabbers to windows"
version = "1.0"
authors = ["Vaxry"]

[hyprpill.build]
output = "hyprpill/hyprpill.so"
steps = [
    "make -C hyprpill all",
]

[hyprtrails]
description = "A plugin to add trails behind moving windows"
version = "1.0"
authors = ["Vaxry"]

[hyprtrails.build]
output = "hyprtrails/hyprtrails.so"
steps = [
    "make -C hyprtrails all",
]

[hyprwinwrap]
description = "A clone of xwinwrap for Hyprland"
version = "1.0"
authors = ["Vaxry"]

[hyprwinwrap.build]
output = "hyprwinwrap/hyprwinwrap.so"
steps = [
    "make -C hyprwinwrap all",
]
