[hyprbars]
description = "A plugin to add title bars to windows"
version = "1.0"
authors = ["Vaxry"]

[hyprbars.build]
output = "hyprbars/hyprbars.so"
steps = [
    "make -C hyprbars all",
]


[hyprpill]
description = "A plugin to add animated pill grabbers to windows"
version = "1.0"
authors = ["Vaxry"]

[hyprpill.build]
output = "hyprpill/hyprpill.so"
steps = [
    "make -C hyprpill all",
]
